carcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
    ]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cars/', views.cars_index, name='cars_index'),
    path('cars/<int:car_id>/', views.cars_detail, name='cars_details'),
    path('cars/create/', views.CarCreate.as_view(), name='car_create'),
    path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='car_update'),
    path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name='car_delete'),
    path('drivers/', views.drivers_index, name='drivers_index'),
    path('drivers/create/', views.DriverCreate.as_view(), name='driver_create'),
    path('drivers/<int:driver_id>/', views.drivers_detail, name='drivers_detail'),
    path('drivers/<int:pk>/update/', views.DriverUpdate.as_view(), name='driver_update'),
    path('drivers/<int:pk>/delete/', views.DriverDelete.as_view(), name='driver_delete'),
    path('cars/<int:car_id>/add_service/', views.add_service, name='add_service'),
    path('cars/<int:car_id>/assoc_driver/<int:driver_id>/', views.assoc_driver, name='assoc_driver'),
    path('cars/<int:car_id>/unassoc_driver/<int:driver_id>/', views.unassoc_driver, name='unassoc_driver'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Driver(models.Model):
    name = models.CharField(max_length=100)
    years_of_experience = models.IntegerField(default=10)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('drivers_detail', kwargs={'pk': self.id})
    

class Car(models.Model):
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    year = models.IntegerField(default=2020)
    drivers = models.ManyToManyField(Driver)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.make

    def get_absolute_url(self):
        return reverse('cars_details', kwargs={'car_id': self.id})

class Service(models.Model):
    CAR_PART = (
        ('T', 'Tires'),
        ('E', 'Engine'),
        ('I', 'Interior')
    )
    date = models.DateField('service_date')
    car_part = models.CharField(max_length=1, choices=CAR_PART, default=CAR_PART[0][0])
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_car_part_display()} on {self.date}'
    
    class Meta:
        ordering = '-date',

main_app/forms.py
from django.forms import ModelForm
from .models import Service

class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = ('date', 'car_part')

main_app/views.py
from django.shortcuts import render, redirect
from .models import Car
from .models import Driver
from .forms import ServiceForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# dummy data

# class Car:
#     def __init__(self, make, model, description, year):
#         self.make = make
#         self.model = model
#         self.description = description
#         self.year = year


# cars = [
#     Car('Lamborghini', 'Aventador', 'Very fast car', 2020),
#     Car('Rolls Royce', 'Wraith', 'Super Comfortable car', 2017),
#     Car('Mercedes Benz', 'S Class', 'Very elegant car', 2018)
# ]

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def cars_index(request):
    cars = Car.objects.filter(user=request.user)
    return render(request, 'cars/index.html', {'cars': cars})

@login_required
def cars_detail(request, car_id):
    car = Car.objects.get(id=car_id)
    service_form = ServiceForm()
    car_driver_ids = car.drivers.all().values_list('id')
    car_driver_cantdrive = Driver.objects.exclude(id__in=car_driver_ids)
    return render(request, 'cars/detail.html', {'car': car, 'service_form': service_form, 'drivers': car_driver_cantdrive})

def add_service(request, car_id):
    form = ServiceForm(request.POST)
    if form.is_valid():
        new_service = form.save(commit=False)
        new_service.car_id = car_id
        new_service.save()
    return redirect('cars_details', car_id=car_id)

@login_required
def assoc_driver(request, car_id, driver_id):
    car = Car.objects.get(id=car_id)
    car.drivers.add(driver_id)
    return redirect('cars_details', car_id=car_id)

@login_required
def unassoc_driver(request, car_id, driver_id):
    car = Car.objects.get(id=car_id)
    car.drivers.remove(driver_id)
    return redirect('cars_details', car_id=car_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
         user = form.save()
         login(request, user)
         return redirect('cars_index')
        else:
            error_message = 'Invalid signup - try again'

    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form , 'error': error_message})


class CarCreate(LoginRequiredMixin, CreateView):
    model = Car
    fields = ('make', 'model', 'description', 'year')
    template_name = 'cars/car_form.html'
    # success_url = '/cars/'
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CarUpdate(LoginRequiredMixin,UpdateView):
    model = Car
    fields = ('description', 'year')
    template_name = 'cars/car_form.html'

class CarDelete(LoginRequiredMixin,DeleteView):
    model = Car
    success_url = '/cars/'
    template_name = 'cars/car_confirm_delete.html'

def drivers_index(request):
    drivers = Driver.objects.all()
    return render(request, 'drivers/index.html', {'drivers': drivers})

class DriverCreate(LoginRequiredMixin,CreateView):
     model = Driver
     fields = '__all__'
     template_name = 'drivers/drivers_form.html'
     success_url = '/drivers/'

def drivers_detail(request, driver_id):
     driver = Driver.objects.get(id=driver_id)
     return render(request, 'drivers/detail.html', {'driver': driver })

class DriverUpdate(LoginRequiredMixin,UpdateView):
     model = Driver
     fields = ('__all__') 
     template_name = 'drivers/drivers_form.html'
     success_url = '/drivers/'

class DriverDelete(LoginRequiredMixin,DeleteView):
     model = Driver
     success_url = '/drivers/'
     template_name = 'drivers/driver_confirm_delete.html'

main_app/templates/about.html
{% extends 'base.html' %}

{% block title %}
<title>About the Car Collector</title>
{% endblock %}

{% block content %}

    <h1>About The Car Collector</h1>

{% endblock%}

main_app/templates/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    {% block title %}
    <title>Car Collector</title>
    {% endblock %}
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper blue-grey darken-1">
                <a href="{% url 'home' %}" class="left brand-logo"> Car Collector</a>
                <ul class="right">
                    <li>
                        <a href="{% url 'about' %}">About</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'cars_index' %}">View All Cars</a>
                    </li>
                    <li>
                        <a href="{% url 'car_create' %}">Add a New Car</a>
                    </li>
                    <li>
                        <a href="{% url 'drivers_index' %}">Drivers</a>
                    </li>
                    <li>
                        <a href="{% url 'driver_create' %}">Add a New Driver</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock%}
    </main>
    <footer class="page-footer grey">
        <p>Copyright &copy; All Rights Reserved Car Collector 2023</p>
    </footer>
</body>
</html>

main_app/templates/cars/car_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Are you sure you want to delete {{ object.make }} </title>
{% endblock %}




{% block content %}
    <h1>Are you sure you want to delete {{ object.make }}? </h1>


<form method="post">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete {{ object.make }}" class="btn red">
    <a href="{% url 'cars_details' object.id %}" class="btn blue">No - Cancel</a>
</form>

{% endblock %}

main_app/templates/cars/car_form.html
{% extends 'base.html' %}

{% block title%}
    {% if object%}
        <title>Update {{ object.make }} </title>
    {% else %}
        <title>Add a Car</title>
    {% endif%}
{% endblock %}


{% block content %}
    {% if object %}
        <h1>Update {{ object.make }} </h1>
    {% else %}
        <h1> New Car</h1>
{% endif %}



<form action="" method="post">
    {% csrf_token %}
    {{ form }}
   
    <input type="submit" value="Submit" class="btn grey">
</form>

{% endblock %}

main_app/templates/cars/detail.html
{% extends 'base.html' %}

{% block title %}
<title>Detail</title>
{% endblock%}

{% block content %}
<h1>Car Detail</h1>

<div class="row">
    <div class="col s6">

   <div class="card">
    <div class="card-content">
        <span class="card-title">{{ car.make }} </span>
        <p>Model: {{ car.model }}</p>
        <p>{{ car.description }}</p>
        <p>Year: {{ car.year }}</p>
    </div>
    <div class="card-action">
        <a href="{% url 'car_update' car.id %}">Update</a>
        <a href="{% url 'car_delete' car.id %}">Delete</a>
    </div>
</div> 
    </div>
    <div class="col s6">
        <form action="{% url 'add_service' car.id %}" method="post">
            {% csrf_token %}
            {{ service_form.as_p }}
            <input type="submit" value="Add Service" class="btn green">
        </form>
        <h4>Car Maintnace: </h4>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Part</th>
                </tr>
            </thead>
            <tbody>
                {% for srvc in car.service_set.all %}
                    <tr>
                        <td>{{ srvc.date }}</td>
                        <td>{{ srvc.get_car_part_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>

<div class="row">
    <div class="col s6">
        <h3>Drivers who can drive {{ car.make }}</h3>
        {% if car.drivers.count %}
        {% for driver in car.drivers.all %}
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{driver.name}}</span>
                    <div class="card-action">
                        <form action="{% url 'unassoc_driver' car.id driver.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Remove" class="btn orange">
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% else %}
        <h5>No drivers yet</h5>
        {% endif %}

    </div>
    <div class="col s6">
        <h3>List of Drivers: </h3>
        {% if drivers.count %}
        {% for driver in drivers %}
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{driver.name}}</span>
                </div>
                <div class="card-action">
                    <form action="{% url 'assoc_driver' car.id driver.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Add" class="btn green">
                    </form>
                </div>
            </div>
        {% endfor %}
        {% else %}
        <h5>Has All available cars</h5>
        {% endif %}

    </div>
</div>

<script>
    const datePickerEl = document.getElementById('id_date')
    const formSelectEl = document.getElementById('id_car_part')

    M.Datepicker.init(datePickerEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    })
    M.FormSelect.init(formSelectEl)
</script>

{% endblock%}

main_app/templates/cars/index.html
{% extends 'base.html' %}

{% block title %}
<title>My Cars</title>
{% endblock%}

{% block content %}
<h1>Cars</h1>


{% for car in cars %}
<div class="card">
    <div class="card-content">
        <span class="card-title">{{ car.make }} </span>
        <p>Model: {{ car.model }}</p>
        <p>{{ car.description }}</p>
        <p>Year: {{ car.year }}</p>
    </div>
</div>

{% endfor %}


{% endblock%}

main_app/templates/drivers/detail.html
{% extends 'base.html' %}

{% block title%}
<title> Driver Details</title>
{% endblock %}

{% block content %}
<h1> Driver Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Driver's name: {{ driver.name }} <br> Years of experience: {{ driver.years_of_experience }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'driver_update' driver.id %}">Edit</a>
        <a href="{% url 'driver_delete' driver.id %}">Delete</a>
      </div>
  </div>

    
  </div>
</div>



{% endblock %}

main_app/templates/drivers/driver_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
<title>Are you sure you want to delete {{object.name }}?</title>
{% endblock %}


{% block content %}
<h1>Are you sure you want to delete {{object.name }}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete {{ object.name }}" class="btn red">
    <a href="{% url 'drivers_detail' object.id %}" class="btn blue">No - Cancel</a>
</form>
{% endblock %}

main_app/templates/drivers/drivers_form.html
{% extends 'base.html' %}

{% block title%}
    {% if object %}
        <title>Update {{ object.name }} </title>
    {% else %}
        <title>Add a Driver</title>
    {% endif %}
{% endblock %}

{% block content%}
{% if object %}
<h1>Update Driver</h1>
{% else%}
<h1>Create Driver</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    
    <table>
        {{ form.as_table }}

    </table>
    
    <input type="submit" value="Submit" class="'btn blue">
</form>
{% endblock%}

main_app/templates/drivers/index.html
{% extends 'base.html' %}

{% block title %}
<title>Drivers</title>
{% endblock %}

{% block content%}
<h1>Drivers</h1>
{% for driver in drivers %}
<a href="{% url 'drivers_detail' driver.id %}">

    <div class="card">
        <div class="card-content">
            <span class="card-title">Driver's name: {{ driver.name }} <br> Years of experience: {{ driver.years_of_experience }}</span>
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>this is the home page</h1>
    
{% endblock %}